# Generated by Django 4.1.2 on 2022-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('blood_grp', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('any_disease', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='xyz@gmail.com', max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
